all: KERNEL.BIN

main.o: main.c
	gcc -ffreestanding -c main.c -o main.o

video.o: video.c
	gcc -c video.c -o video.o

ports.o: ports.c
	gcc -c ports.c -o ports.o

kernel.test: main.o video.o ports.o
	ld -e _main -Ttext 0x1000 -o kernel.test main.o video.o ports.o

kernel.o: kernel.test
	ld -i -e _main -Ttext 0x1000 -o kernel.o main.o video.o ports.o

KERNEL.BIN: kernel.o
	objcopy -R .note -R .comment -S -O binary kernel.o KERNEL.BIN

clean:
	del *.o
	del kernel.test
	del KERNEL.BIN

