
/* generated by util/freeze.py from oneplusone.py */

#include"Python.h"

unsigned char kernel_bytecode[] = {
	99,0,0,0,0,0,0,0,0,2,0,0,0,64,0,0,
	0,115,13,0,0,0,100,0,0,100,0,0,23,71,72,100,
	1,0,83,40,2,0,0,0,105,1,0,0,0,78,40,0,
	0,0,0,40,0,0,0,0,40,0,0,0,0,40,0,0,
	0,0,115,8,0,0,0,60,102,114,111,122,101,110,62,115,
	1,0,0,0,63,1,0,0,0,115,0,0,0,0,
};

struct _frozen frozenModules[] = {
	{"__main__", kernel_bytecode, 94},
	{0, 0, 0} /* sentinel */
};
